-- Automatic score importer support for DWTS Season 35

alter table episodes add column if not exists source_url text;
alter table episodes add column if not exists verification_url text;
alter table episodes add column if not exists scored_at timestamptz;

create table if not exists score_import_runs (
  id bigint generated by default as identity primary key,
  episode_slug text references episodes(slug) on delete cascade,
  ran_at timestamptz not null default now(),
  status text not null,
  source_url text,
  verification_url text,
  details jsonb not null default '{}'::jsonb
);
alter table score_import_runs enable row level security;

create or replace function score_episode(p_episode_slug text)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  result_count int;
  prediction_count int;
begin
  select count(*) into result_count from results where episode_slug=p_episode_slug;
  if result_count=0 then raise exception 'No results loaded for episode'; end if;

  update predictions p
  set points =
    case abs(p.predicted_total-r.total)
      when 0 then 5
      when 1 then 3
      when 2 then 1
      else 0
    end
    + coalesce((
      select count(*)::int
      from generate_subscripts(p.judge_scores,1) s(i)
      where s.i <= coalesce(array_length(r.judge_scores,1),0)
        and p.judge_scores[s.i]=r.judge_scores[s.i]
    ),0)
  from results r
  where p.episode_slug=p_episode_slug
    and r.episode_slug=p_episode_slug
    and r.couple_slug=p.couple_slug;

  update bonus_picks b
  set points =
    case when exists (
      select 1 from results r
      where r.episode_slug=p_episode_slug
        and r.couple_slug=b.highest_slug
        and r.highest
    ) then 5 else 0 end
    +
    case when exists (
      select 1 from results r
      where r.episode_slug=p_episode_slug
        and r.couple_slug=b.eliminated_slug
        and r.eliminated
    ) then 5 else 0 end
  where b.episode_slug=p_episode_slug;

  update couples c
  set active=false
  where exists (
    select 1 from results r
    where r.episode_slug=p_episode_slug
      and r.couple_slug=c.slug
      and r.eliminated
  );

  update episodes
  set status='scored', scored_at=now()
  where slug=p_episode_slug;

  select count(*) into prediction_count from predictions where episode_slug=p_episode_slug;

  return jsonb_build_object(
    'episode_slug',p_episode_slug,
    'results',result_count,
    'predictions_scored',prediction_count
  );
end $$;

revoke all on function score_episode(text) from public, anon, authenticated;
grant execute on function score_episode(text) to service_role;

-- Season schedule used by the automated importer.
update episodes set title='Yacht Rock Night', starts_at='2026-09-29 20:00:00-04', ends_at='2026-09-29 22:00:00-04' where slug='week3';
update episodes set title='Mariah Carey Night', starts_at='2026-10-06 20:00:00-04', ends_at='2026-10-06 22:00:00-04' where slug='week4';
update episodes set title='Week 5', starts_at='2026-10-13 20:00:00-04', ends_at='2026-10-13 22:00:00-04' where slug='week5';
update episodes set title='Dedication Night', starts_at='2026-10-20 20:00:00-04', ends_at='2026-10-20 22:00:00-04' where slug='week6';
update episodes set title='Horror Movie Night', starts_at='2026-10-27 20:00:00-04', ends_at='2026-10-27 22:00:00-04' where slug='week7';
update episodes set title='Disney Night', starts_at='2026-11-02 20:00:00-05', ends_at='2026-11-02 22:00:00-05' where slug='week8';
update episodes set title='Grammy Night', starts_at='2026-11-10 20:00:00-05', ends_at='2026-11-10 22:00:00-05' where slug='week9';
update episodes set title='Semi-Finals', starts_at='2026-11-17 20:00:00-05', ends_at='2026-11-17 22:00:00-05' where slug='week10';
update episodes set title='Finale', starts_at='2026-11-24 20:00:00-05', ends_at='2026-11-24 23:00:00-05' where slug='week11';

-- In the hosted project, project URL and publishable key are stored in Vault
-- as dwts_project_url and dwts_publishable_key. The cron job retries on
-- Tuesdays and Wednesdays until an ended episode is successfully scored.
select cron.schedule(
  'dwts-score-importer',
  '5,35 * * * 2,3',
  $$
  select net.http_post(
    url := (select decrypted_secret from vault.decrypted_secrets where name='dwts_project_url')
      || '/functions/v1/dwts-score-importer',
    headers := jsonb_build_object(
      'Content-Type','application/json',
      'apikey',(select decrypted_secret from vault.decrypted_secrets where name='dwts_publishable_key'),
      'Authorization','Bearer ' || (select decrypted_secret from vault.decrypted_secrets where name='dwts_publishable_key')
    ),
    body := '{}'::jsonb,
    timeout_milliseconds := 20000
  );
  $$
);